# 1. Data Dictionary: Can I make them for Indeed Hiring Lab Sectors?
I'm going to start with seasonally unadjusted first

In [51]:
%pip install pandas

Requirement already satisfied: pandas in c:\git\swytch-team-monkey\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\git\swytch-team-monkey\.venv\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\git\swytch-team-monkey\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\git\swytch-team-monkey\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\git\swytch-team-monkey\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\git\swytch-team-monkey\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [52]:
import pandas as pd
import os
import glob

In [53]:
# === Step 1: Load Dataset ===
DATA_PATH = "C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_unadjusted"

# Get all CSV files in the directory
csv_files = glob.glob(os.path.join(DATA_PATH, "*.csv"))

print(f"Found {len(csv_files)} CSV files:")

for file in csv_files:
    print(f"  - {os.path.basename(file)}")

Found 7 CSV files:
  - accounting_admin-assist_architecture-arts+entertainment_banking+finance_childcare_civilengineering.csv
  - cleaning+sanitation_community+social-service_construction_customer-service_data-analytics_dental_driving.csv
  - education-instruction_electrical-engineering_food-prep+service_hospitality+tourism_human-resources_IT-infrastructure_IT-systems.csv
  - industrial-engineering_installation+maintenance_legal_loading+stocking_logistic-support_management_marketing.csv
  - media+communications_medical-information_medical-technician_nursing_personal-care+home-health_pharmacy_physicians+surgeons.csv
  - production-manafacturing_project-management_retail_sales_scientific-research+development_security+public-safety_software-development.csv
  - sports_therapy_veterinary.csv

<>:2: SyntaxWarning: invalid escape sequence '\g'
<>:2: SyntaxWarning: invalid escape sequence '\g'
C:\Users\rojas\AppData\Local\Temp\ipykernel_5964\428668225.py:2: SyntaxWarning: invalid escape sequence '\g'
  DATA_PATH = "C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_unadjusted"

In [54]:
# Now let's read all CSV files and combine them into one dataframe
dataframes = []

for file in csv_files:
    # Read each CSV file
    df_temp = pd.read_csv(file)
    
    # Add a column to identify which file the data came from
    df_temp['source_file'] = os.path.basename(file)
    
    # Add to our list of dataframes
    dataframes.append(df_temp)
    
    print(f"Loaded {file}: {df_temp.shape[0]} rows, {df_temp.shape[1]} columns")

# Combine all dataframes using pd.concat()
combined_df = pd.concat(dataframes, ignore_index=True)

print(f"\nCombined dataframe shape: {combined_df.shape}")
print(f"Total rows: {len(combined_df)}")
print(f"Total columns: {len(combined_df.columns)}")

Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_unadjusted\accounting_admin-assist_architecture-arts+entertainment_banking+finance_childcare_civilengineering.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_unadjusted\cleaning+sanitation_community+social-service_construction_customer-service_data-analytics_dental_driving.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_unadjusted\education-instruction_electrical-engineering_food-prep+service_hospitality+tourism_human-resources_IT-infrastructure_IT-systems.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_unadjusted\industrial-engineering_installation+maintenance_legal_loading+stocking_logistic-support_management_marketing.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_unadjusted\media+communications_medical-information_medical-technician_nursing_personal-care+home-health_pharmacy_physicians+surgeons.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_unadjusted\production-manafacturing_project-management_retail_sales_scientific-research+development_security+public-safety_software-development.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_unadjusted\sports_therapy_veterinary.csv: 7348 rows, 9 columns

Combined dataframe shape: (93784, 9)
Total rows: 93784
Total columns: 9

In [55]:
# Let's take a look at the combined dataframe
print("\nColumn names:")
print(combined_df.columns.tolist())

print("\nUnique source files:")
print(combined_df['source_file'].unique())

combined_df

Column names:
['__typename', 'dateString', 'countryCode', 'countryName', 'sectorCode', 'sectorName', 'postingType', 'value', 'source_file']

Unique source files:
['accounting_admin-assist_architecture-arts+entertainment_banking+finance_childcare_civilengineering.csv'
 'cleaning+sanitation_community+social-service_construction_customer-service_data-analytics_dental_driving.csv'
 'education-instruction_electrical-engineering_food-prep+service_hospitality+tourism_human-resources_IT-infrastructure_IT-systems.csv'
 'industrial-engineering_installation+maintenance_legal_loading+stocking_logistic-support_management_marketing.csv'
 'media+communications_medical-information_medical-technician_nursing_personal-care+home-health_pharmacy_physicians+surgeons.csv'
 'production-manafacturing_project-management_retail_sales_scientific-research+development_security+public-safety_software-development.csv'
 'sports_therapy_veterinary.csv']

,__typename,dateString,countryCode,countryName,sectorCode,sectorName,postingType,value,source_file
0,HiringLabSectoralPosting,2020-02-01,US,United States,accounting,Accounting,TOTAL,100.00,accounting_admin-assist_architecture-arts+ente...
1,HiringLabSectoralPosting,2020-02-01,US,United States,admin,Administrative Assistance,TOTAL,100.00,accounting_admin-assist_architecture-arts+ente...
2,HiringLabSectoralPosting,2020-02-01,US,United States,arch,Architecture,TOTAL,100.00,accounting_admin-assist_architecture-arts+ente...
3,HiringLabSectoralPosting,2020-02-01,US,United States,arts,Arts & Entertainment,TOTAL,100.00,accounting_admin-assist_architecture-arts+ente...
4,HiringLabSectoralPosting,2020-02-01,US,United States,childcare,Childcare,TOTAL,100.00,accounting_admin-assist_architecture-arts+ente...
...,...,...,...,...,...,...,...,...,...
93779,HiringLabSectoralPosting,2025-09-18,US,United States,therapy,Therapy,NEW,197.37,sports_therapy_veterinary.csv
93780,HiringLabSectoralPosting,2025-09-18,US,United States,veterinary,Veterinary,NEW,160.63,sports_therapy_veterinary.csv
93781,HiringLabSectoralPosting,2025-09-19,US,United States,sports,Sports,NEW,101.65,sports_therapy_veterinary.csv
93782,HiringLabSectoralPosting,2025-09-19,US,United States,therapy,Therapy,NEW,194.54,sports_therapy_veterinary.csv
93783,HiringLabSectoralPosting,2025-09-19,US,United States,veterinary,Veterinary,NEW,156.95,sports_therapy_veterinary.csv

In [56]:
# === Step 2: Generate Data Dictionary ===
def infer_dtype(dtype):
    if pd.api.types.is_string_dtype(dtype):
        return "String"
    elif pd.api.types.is_numeric_dtype(dtype):
        return "Numeric"
    elif pd.api.types.is_bool_dtype(dtype):
        return "Boolean"
    elif pd.api.types.is_datetime64_any_dtype(dtype):
        return "Datetime"
    else:
        return "Other"

dictionary_lines = []
for col in combined_df.columns:
    dtype = infer_dtype(combined_df[col].dtype)
    example = combined_df[col].dropna().iloc[0] if not combined_df[col].dropna().empty else "N/A"
    dictionary_lines.append(f"    - *{col}* → {dtype} (e.g., {example})  # TODO: Add description")

In [57]:
# === Step 3: Print README Section ===
print(dictionary_lines)

['    - *__typename* → String (e.g., HiringLabSectoralPosting)  # TODO: Add description', '    - *dateString* → String (e.g., 2020-02-01)  # TODO: Add description', '    - *countryCode* → String (e.g., US)  # TODO: Add description', '    - *countryName* → String (e.g., United States)  # TODO: Add description', '    - *sectorCode* → String (e.g., accounting)  # TODO: Add description', '    - *sectorName* → String (e.g., Accounting)  # TODO: Add description', '    - *postingType* → String (e.g., TOTAL)  # TODO: Add description', '    - *value* → Numeric (e.g., 100.0)  # TODO: Add description', '    - *source_file* → String (e.g., accounting_admin-assist_architecture-arts+entertainment_banking+finance_childcare_civilengineering.csv)  # TODO: Add description']

## Seasonally Unadjusted Data Dictionary for INDEED Hiring Lab Sectors

'    - *__typename* → String (e.g., HiringLabSectoralPosting)  # TODO: Add description'

'    - *dateString* → String (e.g., 2020-02-01)  # TODO: Add description'

'    - *countryCode* → String (e.g., US)  # TODO: Add description'

'    - *countryName* → String (e.g., United States)  # TODO: Add description'

'    - *sectorCode* → String (e.g., accounting)  # TODO: Add description'

'    - *sectorName* → String (e.g., Accounting)  # TODO: Add description'

'    - *postingType* → String (e.g., TOTAL)  # TODO: Add description'

'    - *value* → Numeric (e.g., 100.0)  # TODO: Add description'

'    - *source_file* → String (e.g., accounting_admin-assist_architecture-arts+entertainment_banking+finance_childcare_civilengineering.csv)  # TODO: Add description

In [58]:
# === Step 1: Load Dataset ===
DATA_PATH = "C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_adjusted"

# Get all CSV files in the directory
csv_files = glob.glob(os.path.join(DATA_PATH, "*.csv"))

print(f"Found {len(csv_files)} CSV files:")

for file in csv_files:
    print(f"  - {os.path.basename(file)}")

Found 7 CSV files:
  - accounting_admin-assist_architecture-arts+entertainment_banking+finance_childcare_civilengineering.csv
  - cleaning+sanitation_community+social-service_construction_customer-service_data-analytics_dental_driving.csv
  - education-instruction_electrical-engineering_food-prep+service_hospitality+tourism_human-resources_IT-infrastructure_IT-systems.csv
  - industrial-engineering_installation+maintenance_legal_loading+stocking_logistic-support_management_marketing.csv
  - media+communications_medical-information_medical-technician_nursing_personal-care+home-health_pharmacy_physicians+surgeons.csv
  - production+manafacturing_project-management_retail_sales_scientific-research+development_security+public-safety_software-dev.csv
  - sports_therapy_veterinary.csv

<>:2: SyntaxWarning: invalid escape sequence '\g'
<>:2: SyntaxWarning: invalid escape sequence '\g'
C:\Users\rojas\AppData\Local\Temp\ipykernel_5964\2950766855.py:2: SyntaxWarning: invalid escape sequence '\g'
  DATA_PATH = "C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_adjusted"

In [59]:
# Now let's read all CSV files and combine them into one dataframe
dataframes2 = []

for file in csv_files:
    # Read each CSV file
    df_temp = pd.read_csv(file)
    
    # Add a column to identify which file the data came from
    df_temp['source_file'] = os.path.basename(file)
    
    # Add to our list of dataframes
    dataframes2.append(df_temp)
    
    print(f"Loaded {file}: {df_temp.shape[0]} rows, {df_temp.shape[1]} columns")

# Combine all dataframes using pd.concat()
combined_df2 = pd.concat(dataframes2, ignore_index=True)

print(f"\nCombined dataframe shape: {combined_df2.shape}")
print(f"Total rows: {len(combined_df2)}")
print(f"Total columns: {len(combined_df2.columns)}")

Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_adjusted\accounting_admin-assist_architecture-arts+entertainment_banking+finance_childcare_civilengineering.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_adjusted\cleaning+sanitation_community+social-service_construction_customer-service_data-analytics_dental_driving.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_adjusted\education-instruction_electrical-engineering_food-prep+service_hospitality+tourism_human-resources_IT-infrastructure_IT-systems.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_adjusted\industrial-engineering_installation+maintenance_legal_loading+stocking_logistic-support_management_marketing.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_adjusted\media+communications_medical-information_medical-technician_nursing_personal-care+home-health_pharmacy_physicians+surgeons.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_adjusted\production+manafacturing_project-management_retail_sales_scientific-research+development_security+public-safety_software-dev.csv: 14406 rows, 9 columns
Loaded C:\git\SwYtch-Team-Monkey\Raw_Data\Indeed_Hiring_Lab\Sectors\seasonally_adjusted\sports_therapy_veterinary.csv: 6174 rows, 9 columns

Combined dataframe shape: (92610, 9)
Total rows: 92610
Total columns: 9

In [60]:
# Let's take a look at the combined dataframe
print("\nColumn names:")
print(combined_df2.columns.tolist())

print("\nUnique source files:")
print(combined_df2['source_file'].unique())

combined_df2

Column names:
['__typename', 'dateString', 'countryCode', 'countryName', 'sectorCode', 'sectorName', 'postingType', 'value', 'source_file']

Unique source files:
['accounting_admin-assist_architecture-arts+entertainment_banking+finance_childcare_civilengineering.csv'
 'cleaning+sanitation_community+social-service_construction_customer-service_data-analytics_dental_driving.csv'
 'education-instruction_electrical-engineering_food-prep+service_hospitality+tourism_human-resources_IT-infrastructure_IT-systems.csv'
 'industrial-engineering_installation+maintenance_legal_loading+stocking_logistic-support_management_marketing.csv'
 'media+communications_medical-information_medical-technician_nursing_personal-care+home-health_pharmacy_physicians+surgeons.csv'
 'production+manafacturing_project-management_retail_sales_scientific-research+development_security+public-safety_software-dev.csv'
 'sports_therapy_veterinary.csv']

,__typename,dateString,countryCode,countryName,sectorCode,sectorName,postingType,value,source_file
0,HiringLabSectoralPosting,2020-02-01,US,United States,accounting,Accounting,TOTAL,100.00,accounting_admin-assist_architecture-arts+ente...
1,HiringLabSectoralPosting,2020-02-01,US,United States,admin,Administrative Assistance,TOTAL,100.00,accounting_admin-assist_architecture-arts+ente...
2,HiringLabSectoralPosting,2020-02-01,US,United States,arch,Architecture,TOTAL,100.00,accounting_admin-assist_architecture-arts+ente...
3,HiringLabSectoralPosting,2020-02-01,US,United States,arts,Arts & Entertainment,TOTAL,100.00,accounting_admin-assist_architecture-arts+ente...
4,HiringLabSectoralPosting,2020-02-01,US,United States,childcare,Childcare,TOTAL,100.00,accounting_admin-assist_architecture-arts+ente...
...,...,...,...,...,...,...,...,...,...
92605,HiringLabSectoralPosting,2025-09-18,US,United States,therapy,Therapy,TOTAL,184.79,sports_therapy_veterinary.csv
92606,HiringLabSectoralPosting,2025-09-18,US,United States,veterinary,Veterinary,TOTAL,147.52,sports_therapy_veterinary.csv
92607,HiringLabSectoralPosting,2025-09-19,US,United States,sports,Sports,TOTAL,146.81,sports_therapy_veterinary.csv
92608,HiringLabSectoralPosting,2025-09-19,US,United States,therapy,Therapy,TOTAL,184.71,sports_therapy_veterinary.csv
92609,HiringLabSectoralPosting,2025-09-19,US,United States,veterinary,Veterinary,TOTAL,147.81,sports_therapy_veterinary.csv

In [61]:
# === Step 2: Generate Data Dictionary ===
def infer_dtype(dtype):
    if pd.api.types.is_string_dtype(dtype):
        return "String"
    elif pd.api.types.is_numeric_dtype(dtype):
        return "Numeric"
    elif pd.api.types.is_bool_dtype(dtype):
        return "Boolean"
    elif pd.api.types.is_datetime64_any_dtype(dtype):
        return "Datetime"
    else:
        return "Other"

dictionary_lines = []
for col in combined_df2.columns:
    dtype = infer_dtype(combined_df2[col].dtype)
    example = combined_df2[col].dropna().iloc[0] if not combined_df2[col].dropna().empty else "N/A"
    dictionary_lines.append(f"    - *{col}* → {dtype} (e.g., {example})  # TODO: Add description")

In [62]:
# === Step 3: Print README Section ===
print(dictionary_lines)

['    - *__typename* → String (e.g., HiringLabSectoralPosting)  # TODO: Add description', '    - *dateString* → String (e.g., 2020-02-01)  # TODO: Add description', '    - *countryCode* → String (e.g., US)  # TODO: Add description', '    - *countryName* → String (e.g., United States)  # TODO: Add description', '    - *sectorCode* → String (e.g., accounting)  # TODO: Add description', '    - *sectorName* → String (e.g., Accounting)  # TODO: Add description', '    - *postingType* → String (e.g., TOTAL)  # TODO: Add description', '    - *value* → Numeric (e.g., 100.0)  # TODO: Add description', '    - *source_file* → String (e.g., accounting_admin-assist_architecture-arts+entertainment_banking+finance_childcare_civilengineering.csv)  # TODO: Add description']

## Seasonally Adjusted Sector Data Dictionary for INDEED Hiring Lab Sectors

'    - *__typename* → String (e.g., HiringLabSectoralPosting)  # TODO: Add description'

'    - *dateString* → String (e.g., 2020-02-01)  # TODO: Add description'

'    - *countryCode* → String (e.g., US)  # TODO: Add description'

'    - *countryName* → String (e.g., United States)  # TODO: Add description'

'    - *sectorCode* → String (e.g., accounting)  # TODO: Add description'

'    - *sectorName* → String (e.g., Accounting)  # TODO: Add description'

'    - *postingType* → String (e.g., TOTAL)  # TODO: Add description'

'    - *value* → Numeric (e.g., 100.0)  # TODO: Add description'

'    - *source_file* → String (e.g., accounting_admin-assist_architecture-arts+entertainment_banking+finance_childcare_civilengineering.csv)  # TODO: Add description'

## Seasonally Unadjusted Data Dictionary for INDEED Hiring Lab Sectors

'    - *__typename* → String (e.g., HiringLabSectoralPosting)  # TODO: Add description'

'    - *dateString* → String (e.g., 2020-02-01)  # TODO: Add description'

'    - *countryCode* → String (e.g., US)  # TODO: Add description'

'    - *countryName* → String (e.g., United States)  # TODO: Add description'

'    - *sectorCode* → String (e.g., accounting)  # TODO: Add description'

'    - *sectorName* → String (e.g., Accounting)  # TODO: Add description'

'    - *postingType* → String (e.g., TOTAL)  # TODO: Add description'

'    - *value* → Numeric (e.g., 100.0)  # TODO: Add description'

'    - *source_file* → String (e.g., accounting_admin-assist_architecture-arts+entertainment_banking+finance_childcare_civilengineering.csv)  # TODO: Add description

# CONCLUSION: Both headlines contain the same columns